version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.1
    steps:
      - checkout
      - run:
          name: change-directory
          command: 'cd oss-front'
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: build
          command: npm run build
